name: loupe # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
adopt-info: loupe
grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots
layout:
  /usr/share/loupe:
    symlink: $SNAP/usr/share/loupe
parts:    
  gtk4:
    source: https://gitlab.gnome.org/GNOME/gtk.git
    source-commit: '10825cdc720d15c4185c8d7c3ce180f227498c94'
# ext:updatesnap
#   version-format:
#     ignore-odd-minor: true
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dbroadway-backend=false
      - -Dx11-backend=true
      - -Dwayland-backend=true
      - -Dwin32-backend=false
      - -Dmacos-backend=false
      - -Dintrospection=disabled
      - -Dgtk_doc=false
      - -Ddemos=false
      - -Dbuild-examples=false
      - -Dbuild-tests=false
      - -Dmedia-gstreamer=disabled
      - -Ddemos=false
      - -Dbuild-testsuite=false
      - -Dbuild-examples=false
      - -Dbuild-tests=false
      - -Dprint-cups=enabled
    organize:
      usr/lib/gtk-4.0: usr/lib/$CRAFT_ARCH_TRIPLET/gtk-4.0
    build-packages:
      - libxkbcommon-dev
      - libcups2-dev
      - libcolord-dev
      - libxrandr-dev
      - libxcursor-dev
      - libisocodes-dev
      - libxcomposite-dev
      - libxdamage-dev
      - libxfixes-dev
      - libxi-dev
      - libxkbfile-dev
      - libxml2-utils
    stage:
      - -usr/bin/wayland-scanner
      - -usr/lib/*/libwayland-client.so.0.20.0
      - -usr/lib/*/libwayland-server.so.0.20.0
  libadwaita:
    after: [ gtk4 ]
    source: https://gitlab.gnome.org/GNOME/libadwaita.git
    source-commit: 'a97fa1541229271610ce47a4a1dcea4c0340b84c'
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Ddebug=true
      - -Dintrospection=enabled
      - -Dvapi=true
      - -Dtests=false
      - -Dexamples=false
    build-environment:
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH
    build-packages:
      - sassc
  glib:
    source: https://gitlab.gnome.org/GNOME/glib.git
    source-tag: '2.76.1'
# ext:updatesnap
#   version-format:
#     ignore-odd-minor: true
    source-depth: 1
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
      - -Dtests=false
    override-build: |
      set -eux
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/glib-2.0/
      cp $CRAFT_PART_INSTALL/usr/bin/{gio-querymodules,glib-compile-schemas} $CRAFT_PART_INSTALL/usr/lib/$CRAFT_ARCH_TRIPLET/glib-2.0/
    build-packages:
      - libmount-dev
      
  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'

  loupe:
    after: [ rustup, glib, libadwaita ]
    # See 'snapcraft plugins'
    plugin: meson
    source: https://gitlab.gnome.org/GNOME/Incubator/loupe.git
    source-tag: '44.3'
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/lib/pkgconfig:/snap/gnome-42-2204-sdk/current/usr/share/pkgconfig${PKG_CONFIG_PATH:+:$PKG_CONFIG_PATH}
    build-packages:
      - libyaml-dev
      - libxmlb-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-bad1.0-dev
    meson-parameters:
      - --prefix=/usr
      - -Doptimization=3
    parse-info: [ usr/share/metainfo/org.gnome.Loupe.metainfo.xml ]

slots:
  snapshot:
    interface: dbus
    bus: session
    name: org.gnome.Loupe
apps:
  snapshot:
    command: usr/bin/loupe
    desktop: usr/share/applications/org.gnome.Loupe.desktop
    extensions: [ gnome ]
    common-id: org.gnome.Loupe
    plugs:
      - process-control
